auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Cheng Quan 
url: http://cheng-quan.github.io/
feed: /atom.xml
author_info: <a href="http://cheng-quan.github.io/">程 权</a>
